<img align="left" src="Python-logo.png" width=120 style="padding: 20px">

# Minicurso Python

24/10 e 25/10

Andressa Wille (andressaw2@gmail.com)

## Parte 1 - Introdução ao Python e Numpy

## 1. Descobrindo Python e Notebooks

Python é uma das linguagens de programação mais populares atualmente por ser mais simples e intuitiva que outras linguagens. É muito importante nas áreas de ciência, matemática e inteligência artificial.

Visite o site oficial: https://www.python.org/

Já notebooks são arquivos que contém vários tipos de células, de código, texto e outputs, que facilitam o entendimento do que você está programando. Temos os Jupyter Notebooks, que podem ser executados no Jupyter Lab (ou no Jupyter Notebook, uma versão mais antiga) e também temos o Google Colab.

Visite o site oficial do Jupyter: https://jupyter.org/try

O Google Colab pode ser acessado diretamente no seu Google Drive, não é preciso instalar nada.

Os códigos em Python também podem ser escritos em um arquivo simples do bloco de notas e serem executados no terminal. Basta salvar o arquivo com a extensão .py e executar no terminal:

`python arquivo.py`

Mas nesse minicurso, vamos utilizar os notebooks.

Informações adicionais e detalhes de instalação estão no arquivo primeiros-passos.pdf.

### Células do Notebook

Existem células de código (code), texto formatado (markdown) e texto puro (raw) no Jupyter Notebook. No Google Colab não há célula raw.

#### Célula Markdown

As células markdown são boas para escrever textos descritivos com formatação de fontes maiores ou menores, negrito, itálico, colorida, com imagens, tabelas e equações (LaTeX).

Vamos ver alguns exemplos.

Estilos de texto:

# Título 1
## Título 2
### Título 3
#### Título 4
##### Título 5
###### Título 6


**texto em negrito**

_texto em itálico_

~~texto riscado~~


`texto estilo comando` 

<font color='red'>Texto vermelho</font>

<font color='yellow'>Texto amarelo</font>

> **Agora é sua vez!**
> 
> Faça uma célula com um texto em rosa.

Links:

[Mais sobre markdown](https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd)

Quotes:
> Algum texto importante


Lista:
- item
- item
- item

ou

- [x] item feito
- [ ] item não feito
- [ ] item não feito


Equações (centralizada ou não):

$e^{i\pi} + 1 = 0$

$$E = mc^2$$

> **Agora é sua vez!**
> 
> Faça uma célula com uma equação.

Tabela:

|  x  |  y  |  z  |
|-----|-----|-----|
| x1  | y1  | z1  |
| x2  | y2  | z2  |
| x3  | y3  | z3  |
| x4  | y4  | z4  |

E tem muito mais! Várias coisas podem ser feitas nas células markdown, mas o principal é isso.

#### Célula Code

Agora vamos fazer um exemplo de célula de código. Nessas células escrevemos o programa que desejamos executar. Ele pode produzir um output ou não.

O comando `print()` imprime alguma coisa na tela. Observe que a linha #exemplo não faz nada no código. Quando queremos escrever algo que não vai ser executado, ou seja, um comentário usamos #.

In [3]:
#exemplo
print('Hello world!')

Hello world!


____

## 2. Introdução à programação em Python

Agora vamos dar os primeiros passos na programação em Python. Aguarde as instruções e execute os exemplos.

### Variáveis

As variáveis, na programação, definem os valores/dados que serão manipulados em um programa.

Os principais tipos de dados são: números (int, float), texto (str), coleções (list, dict), booleanos (bool). Para saber o tipo de um dado, use o comando `type()`.

In [9]:
a = 1
b = 1.3
c = '1'
d = True
e = [1, 2, 3]

In [16]:
type(a)

int

> **Agora é sua vez!**
> 
> Descubra os tipos das outras variáveis criadas.

### Operações matemáticas básicas

`+` soma

`-` subtração

`*` multiplicação

`/` divisão

`**` potência

`%` resto da divisão

`=` atribuição

In [24]:
n1 = 4
n2 = 2

In [27]:
n1 + n2

6

> **Agora é sua vez!**
> 
> Teste as outras operações.

### Strings

In [30]:
texto = 'oi!'

In [31]:
print(texto)

oi!


> **Agora é sua vez!**
> 
> Troque o texto por outra coisa e imprima.

In [32]:
nome = 'Andressa'

In [34]:
print(f'Meu nome é {nome}.')

Meu nome é Andressa.


In [35]:
print(f'A letra inicial do meu nome é {nome[0]}.')

A letra inicial do meu nome é A.


In [36]:
nome.upper()

'ANDRESSA'

In [37]:
nome.lower()

'andressa'

> **Agora é sua vez!**
> 
> Teste com o seu nome.

In [42]:
palavra = 'melancia'

In [43]:
palavra.capitalize()

'Melancia'

In [44]:
palavra.split('l')

['me', 'ancia']

Você também pode pedir que o usuário escreva uma palavra, e assim você não estará definindo a variável diretamente na célula.

In [6]:
palavra = str(input('Digite uma palavra: '))

Digite uma palavra:  sim


In [10]:
print(f'Você digitou "{palavra}". ')

Você digitou "sim" 


### True e False

`==` igual

`!=` diferente

In [46]:
y = 2
x = 3

In [49]:
y == x

False

> **Agora é sua vez!**
> 
> Troque o == por != na célula acima.

In [50]:
y + 1 == x

True

### Listas

In [51]:
lista = [1, 2, 3, 4, 5]

In [54]:
print(lista[0])
print(lista[-1])
print(lista[0:3])

1
5
[1, 2, 3]


Substituir um elemento da lista:

In [55]:
lista[1] = 100
lista

[1, 100, 3, 4, 5]

> **Agora é sua vez!**
> 
> Crie uma lista com 6 elementos e troque o terceiro.

Ordenar lista:

In [56]:
numeros = [3, 7, 5, 10, 22, -1]
sorted(numeros)

[-1, 3, 5, 7, 10, 22]

In [60]:
letras = ['x', 'b', 'd', 'c', 'a']
sorted(letras)

['a', 'b', 'c', 'd', 'x']

Manipulando listas:

In [62]:
mistura = numeros + letras
mistura

[3, 7, 5, 10, 22, -1, 'x', 'b', 'd', 'c', 'a']

In [69]:
lista2 = [4, 5, 6]
4*lista2

[4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]

Como podem ser feitas operações matemáticas como soma e multiplicação? Vamos ver arrays com `numpy` mais à frente.

### Dicionários

In [76]:
notas = {'João':5.0, 
        'Maria':9.4,
        'Vanessa':7.8,
        'Leo':6.0}
notas

{'João': 5.0, 'Maria': 9.4, 'Vanessa': 7.8, 'Leo': 6.0}

In [71]:
notas.keys()

dict_keys(['João', 'Maria', 'Vanessa', 'Leo'])

In [72]:
notas.values()

dict_values([5.0, 9.4, 7.8, 6.0])

In [73]:
notas['Leo']

6.0

In [75]:
notas['Pedro'] = 10.0
notas

{'João': 5.0, 'Maria': 9.4, 'Vanessa': 7.8, 'Leo': 6.0, 'Pedro': 10.0}

> **Agora é sua vez!**
> 
> Crie um dicionário que contenha itens de supermercado e seu preço.

### Condições

Na vida, tomamos decisões o tempo todo. Na programação não é diferente. Mas como o programa sabe se tem que executar uma tarefa ou outra? Para isso, temos a estrutura **if-else**. Se uma condição é satisfeita, então um bloco de comandos é executado; senão, outro bloco de comandos roda. 

Vamos fazer um exemplo que verifique se um número é par ou ímpar:

In [22]:
a = 3
if a%2 == 0:
    print('É par.')
else:
    print('É ímpar.')

É ímpar.


> **Agora é sua vez!**
> 
> Acima, altere a variável 'a' para um número ímpar e teste. Abaixo, crie um programa que imprima se uma variável é maior ou menor que 200.

Também temos a estrutura **if-elif-else**:

In [25]:
cor = str(input('O semáforo está '))
if cor == 'verde':
    print('Continue!')
elif cor == 'amarelo':
    print('Atenção!')
else:
    print('Pare!')

O semáforo está  vermelho


Pare!


### Loops

Várias vezes na programação vamos precisar que um código ou parte de dele seja repetido. Para não precisar escrever várias vezes a mesma coisa, podemos usar estruturas de repetição, ou loops.

Em Python, temos os comandos **for** e **while**.

Para entender melhor, vamos partir para os exemplos. Repare na indentação.

In [4]:
#imprimir números de 1 a 10
for i in range(1, 11, 1):
    print(i)

1
2
3
4
5
6
7
8
9
10


> **Agora é sua vez!**
> 
> Altere o programa acima, trocando o passo para 2. O que acontece?

In [12]:
#gerador de tabuada
n = int(input('Qual tabuada voce quer saber? Digite um numero de 1 a 10: '))
for i in range(0, 11, 1):
    resultado = n * i
    print(f'{n} X {i} = {resultado}')

Qual tabuada voce quer saber? Digite um numero de 1 a 10:  2


2 X 0 = 0
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20


In [20]:
#reprovar ou aprovar
turma1 = [9.0, 3.6, 5.9, 7.5, 10.0]

for nota in turma1:
    if nota >= 6.0:
        print(f'{nota} - Aprovado')
    else:
        print(f'{nota} - Reprovado')

9.0 - Aprovado
3.6 - Reprovado
5.9 - Reprovado
7.5 - Aprovado
10.0 - Aprovado


In [17]:
#nome com mais de 3 caracteres
nome = str(input('Digite o seu nome: '))
while len(nome) <= 3:
    nome = input('Seu nome deve ter mais de 3 caracteres. Digite o seu nome: ')
print('Ok.')

Digite o seu nome:  leo
Seu nome deve ter mais de 3 caracteres. Digite o seu nome:  pi
Seu nome deve ter mais de 3 caracteres. Digite o seu nome:  quito


Ok.


In [18]:
#confirmação de senha
print('Confirmação de senha')
senha1 = str(input('Digite a senha: '))
senha2 = str(input('Confirme a senha: '))
while senha1 != senha2:
    print('Senha errada, digite novamente.')
    senha1 = input('Digite a senha: ')
    senha2 = input('Confirme a senha: ')
print('Senha confirmada.')

Confirmação de senha


Digite a senha:  lia
Confirme a senha:  lea


Senha errada, digite novamente.


Digite a senha:  lia
Confirme a senha:  lia


Senha confirmada.


> **Agora é sua vez!**
> 
> Faça um programa que leia a idade de um usuário e verifique se ela é possível: não existe uma pessoa com idade menor que zero ou maior do que, digamos, 120 anos.

___________

## 3. NumPy

Numerical Python ou NumPy é uma biblioteca essencial para cálculos e tarefas matemáticas.

Visite o site oficial: https://numpy.org/

Vejamos alguns exemplos a seguir. Primeiro, precisamos importar a biblioteca:

In [3]:
import numpy as np

### Operações com arrays

Fazer operações com numpy arrays é bem mais prático. Os arrays no numpy podem ter mais de uma dimensão.

In [16]:
lista = [1,2,3]
x = np.array(lista)
x

array([1, 2, 3])

In [5]:
y = np.array([[4,5,6],[7,8,9],[10,11,12]])
y

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Matriz transposta:

In [6]:
y_trans = y.T
y_trans

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

Criar uma sequência:

In [8]:
a = np.arange(0,31,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

Operações:

In [27]:
b = [4, 5, 8, 3, 1]
b = np.array(b)

c = [5, 21, 0, 9, 6]
c = np.array(c)

In [28]:
b+c

array([ 9, 26,  8, 12,  7])

In [33]:
bc = np.concatenate([b,c])
bc

array([ 4,  5,  8,  3,  1,  5, 21,  0,  9,  6])

In [29]:
4*b

array([16, 20, 32, 12,  4])

Operações trigonométricas:

In [13]:
pi = np.pi
z = np.arange(0,4*pi,pi/2)
z

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531,
        7.85398163,  9.42477796, 10.99557429])

In [14]:
np.sin(z)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16,  1.0000000e+00,  3.6739404e-16, -1.0000000e+00])

> **Agora é sua vez!**
> 
> Teste outras funções trigonométricas: cosseno e tangente.

Somar elementos, fazer média:


In [18]:
lista2 = [5, 8, 9, 8]

soma = np.sum(lista2)
print(soma)

media = np.mean(lista2)
print(media)

30
7.5


Encontrar valor máximo e mínimo:

In [23]:
maximo = np.max(lista2)
print(maximo)

minimo = np.min(lista2)
print(minimo)

9
5


### Leitura e escrita de arquivos

Quando estamos trabalhando com dados, precisamos ler e escrever arquivos para fazer análises, plotar gráficos e etc.

Escrita:

In [34]:
r = np.array([1, 2, 3, 4, 5, 6, 7, 8])
v = np.array([4, 7, 8, 10, 11, 15, 20, 21])

In [35]:
out = np.transpose([r, v])
name = 'exemplo.txt'
np.savetxt(name, out, header='raio      velocidade', fmt='%1.6e')

Leitura:

In [36]:
raio, vel = np.loadtxt('exemplo.txt', usecols=(0,1), unpack=True)

In [37]:
raio

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [38]:
vel

array([ 4.,  7.,  8., 10., 11., 15., 20., 21.])

_____________________

Na próxima aula vamos aprender a plotar alguns gráficos... Até lá!